CREATE TABLE CONTACT (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    PRIMARY_EMAIL VARCHAR(255),
    BIRTHDAY DATE
);

CREATE TABLE PHONENUMBER (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NUMBER VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    PHONE_TYPE VARCHAR(255),
    CONTACT_ID BIGINT NOT NULL CONSTRAINT CONTACT_ID_FK REFERENCES CONTACT(ID) ON DELETE CASCADE ON UPDATE RESTRICT
);